# Configuration file for SurvivalGames
# SurvivalGames by @McpeBooster

#If you need help, look at the ReadMe.md

#Language of the Plugin: eng/deu/cze
language: eng

#Array with all GameId
GameId: []

#Here comes the Arena configuration